version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "SqlServer123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1533:1433"
    volumes:
      - new-mssql-data:/var/opt/mssql  # ✅ Mount volume here

volumes:
  new-mssql-data:
